curl 'https://images.igdb.com/igdb/image/upload/t_thumb/adbbuepfcnjzo8fxumc5.jpg' --output 1497.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/m3mj346jzlrjwhtdven7.jpg' --output 463.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cl1hw.jpg' --output 1940.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/xx9lm1jz1gldwhigj6xv.jpg' --output 1109.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/msudqikl0g5x7plkueea.jpg' --output 1149.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/bvgbtacvqqsfyp3ksmhk.jpg' --output 1752.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/rj4gzadlr6pknfmwulth.jpg' --output 634.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cmj0b7wd2kwp4r6gmi48.jpg' --output 776.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/fywo56bx6ef224ugfnia.jpg' --output 1396.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/wgwrpjvytoctmeubee8g.jpg' --output 1623.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/wruohez9dqizgw8zk3cb.jpg' --output 1582.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/l2ovfeiyw7cq4uooy1vi.jpg' --output 835.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/a12i9e3turhxxvgpdrkd.jpg' --output 611.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/c3ps3hq8i8uhar1svwmt.jpg' --output 1739.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cl1hl.jpg' --output 1929.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/xo7j8jzzs4vrz6rb7wt8.jpg' --output 1453.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/f61lbv8ylqyb6bobkhq5.jpg' --output 1555.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/svplxuxn983cwmohg6w3.jpg' --output 968.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ku5fyyxinnqfockewdsu.jpg' --output 1544.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/op07qjecchcnloncktzq.jpg' --output 1389.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/fi4b8eo3lzpxd8pg1b8p.jpg' --output 1351.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/bd2n6z08fikzeceh4rvn.jpg' --output 528.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/yqouig3mtvzeqty1n0zk.jpg' --output 750.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/gp3umi2sjz9usxfxteop.jpg' --output 819.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/k8wkhkfbw3sk6owfm8mp.jpg' --output 914.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/wudum9znehdha7u1mqls.jpg' --output 567.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/kb9sawzyaxzrz893k6i3.jpg' --output 421.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ecmindux8jbrrzq3pta1.jpg' --output 7.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ypol3bodmtdiszldmwwx.jpg' --output 1413.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/brikw5stecwn0nljedjy.jpg' --output 1223.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/l0dtmb2gkq3nwodtp0lk.jpg' --output 782.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/wiafwsqrrutku99o3ryd.jpg' --output 1235.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/a9h6lrgtsifaumvrkhdc.jpg' --output 1256.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cl1fu.jpg' --output 1866.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/uyfj13j9g7tf49idfp7d.jpg' --output 1004.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cl1jc.jpg' --output 1992.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/axhaqcjs6klzovnfnwwf.jpg' --output 1382.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ljaknmzizln9buncdzf7.jpg' --output 137.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/y4h6dcx4rhvq9x4cd2xx.jpg' --output 1180.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/wijwce4vydwaxtrxncqn.jpg' --output 1384.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/cl1ic.jpg' --output 1956.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/gvgzgca5jcc6txinkurh.jpg' --output 1360.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ovsft3nsdeo4f2bwu0wc.jpg' --output 988.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/eomwezy37y2y1ll8jb8j.jpg' --output 898.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/ai5v41vwx1s6dvgdflb1.jpg' --output 535.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/rihn5mrwexmsbwsbsp6s.jpg' --output 511.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/kftkdku2or8nmrw1wfnv.jpg' --output 474.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/eetykswccdbz3emdwejj.jpg' --output 442.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/gmrfwnitutj3irwpykzu.jpg' --output 1009.jpg
curl 'https://images.igdb.com/igdb/image/upload/t_thumb/fvu0y85qp2rygbiihwgk.jpg' --output 1490.jpg
